### ISSUE TITLE
Cannot start service django: driver failed programming external connectivity on endpoint comeo_django_1

### ISSUE THREAD

**Issue by stephendwolff** [ipostolaki/Comeo#2]
Hi Ilia, I had a go at running your project, looks very interesting, but i'm getting an error when starting the docker containers. The full trace here:

```
Comeo-master $ make run
docker-compose stop django  # for restart cases, when already running
docker-compose up
Starting comeo_pg_database_1
Starting comeo_neo_1
Starting comeo_rabbit_1
Starting comeo_django_1

ERROR: for django  Cannot start service django: driver failed programming external connectivity on endpoint comeo_django_1 (0e09c4fc6101d275fc9ab117daf94120a04a3fba7b584e07456814fdb9bad3dc): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
make: *** [run] Error 1
```

Any ideas?

**Comment by ipostolaki** [comment]
Hi Stephen @stephendwolff,
I have tried to reproduce the same situation. It seems that this issue is caused by another docker container running in the system. And for this container, port 80 is already allocated.

`docker ps` may clarify what's going on.
And `docker stop $(docker ps -q)` will stop all currently running containers.

**Comment by stephendwolff** [comment]
yep - i tried docker ps - nothing showed up. I could see com.docke in the list for port 80 with:

lsof -Pn -i4 | grep LISTEN

I re-started my machine (twice!), and reset docker, and then port 80 seemed to clear. However - haven't quite got comeo running, as i ran out of time.
